# Generated by Django 6.0.1 on 2026-01-30 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('posto_atual', models.IntegerField(choices=[(1, 'Posto 1 - Preparação'), (2, 'Posto 2 - Pré-Montagem'), (3, 'Posto 3 - Soldadura'), (4, 'Posto 4 - Limpeza'), (5, 'Posto 5 - Pintura'), (6, 'Posto 6 - Montagem')], default=1)),
                ('status_global', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acessorio')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto_padrao', models.IntegerField(choices=[(1, 'Posto 1 - Preparação'), (2, 'Posto 2 - Pré-Montagem'), (3, 'Posto 3 - Soldadura'), (4, 'Posto 4 - Limpeza'), (5, 'Posto 5 - Pintura'), (6, 'Posto 6 - Montagem')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posto', models.IntegerField(choices=[(1, 'Posto 1 - Preparação'), (2, 'Posto 2 - Pré-Montagem'), (3, 'Posto 3 - Soldadura'), (4, 'Posto 4 - Limpeza'), (5, 'Posto 5 - Pintura'), (6, 'Posto 6 - Montagem')])),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='producao.ordemproducao')),
            ],
        ),
    ]
