# Generated by Django 6.0.1 on 2026-01-30 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('stock_atual', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_sequencia', models.IntegerField(help_text='Ordem do posto no fluxo (ex: 1, 2, 3...)', unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordem_sequencia'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do funcionário (ex: João Silva)', max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postos', models.ManyToManyField(help_text='Postos onde este funcionário pode trabalhar', related_name='funcionarios', to='producao.posto')),
            ],
        ),
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('pecas_necessarias', models.ManyToManyField(blank=True, help_text='Peças necessárias para fabricar este acessório', to='producao.peca')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateField(blank=True, help_text='Data prevista para conclusão', null=True)),
                ('status_global', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('acessorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.acessorio')),
                ('funcionario_designado', models.ForeignKey(blank=True, help_text='Atribuir a um funcionário específico (Opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.funcionario')),
                ('posto_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='producao.posto')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='producao.ordemproducao')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producao.posto')),
            ],
        ),
    ]
