# Generated by Django 6.0.1 on 2026-01-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='data_prevista',
            field=models.DateField(blank=True, help_text='Data prevista para conclusão', null=True),
        ),
    ]
